#O docker compose é uma ferramente que ajuda a definir e compartilhar múltiplos containers

version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=reis
      - POSTGRES_PASSWORD=337711
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/docker
    links:
      - database
    depends_on: 
      - database

volumes:
  pgdata:
    driver: local
#vou pegar o docker file da raiz e mandar p a pasta dele
#defino o service com base no diretório do Dockerfile