#O docker compose é uma ferramente que ajuda a definir e compartilhar múltiplos containers

version: "3.7"

services:
  app: 
    build: .
    container_name: rentx
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/docker  
      #vou pegar o docker file da raiz e mandar p a pasta dele
      #defino o service com base no diretório do Dockerfile